// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# REST API interface for 1Password Connect.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "http://localhost:8080/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Retrieve a list of API Requests that have been made.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listApiActivity(map<string|string[]> headers = {}, *ListApiActivityQueries queries) returns APIRequest[]|error {
        string resourcePath = string `/activity`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get all Vaults
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listVaults(map<string|string[]> headers = {}, *ListVaultsQueries queries) returns Vault[]|error {
        string resourcePath = string `/vaults`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Vault details and metadata
    #
    # + vaultUuid - The UUID of the Vault to fetch Items from
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getVault(string vaultUuid, map<string|string[]> headers = {}) returns Vault|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get all items for inside a Vault
    #
    # + vaultUuid - The UUID of the Vault to fetch Items from
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listItems(string vaultUuid, map<string|string[]> headers = {}, *ListItemsQueries queries) returns Item[]|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a new Item
    #
    # + vaultUuid - The UUID of the Vault to create an Item in
    # + headers - Headers to be sent with the request 
    # + payload - The Item to create, including its fields, sections and URLs 
    # + return - OK 
    remote isolated function createItem(string vaultUuid, FullItem payload, map<string|string[]> headers = {}) returns FullItem|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the details of an Item
    #
    # + vaultUuid - The UUID of the Vault to fetch Item from
    # + itemUuid - The UUID of the Item to fetch
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getItem(string vaultUuid, string itemUuid, map<string|string[]> headers = {}) returns FullItem|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update an Item
    #
    # + vaultUuid - The UUID of the Item's Vault
    # + itemUuid - The UUID of the Item to update
    # + headers - Headers to be sent with the request 
    # + payload - The complete Item to store in place of the existing one 
    # + return - OK 
    remote isolated function updateItem(string vaultUuid, string itemUuid, FullItem payload, map<string|string[]> headers = {}) returns FullItem|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete an Item
    #
    # + vaultUuid - The UUID of the Vault the item is in
    # + itemUuid - The UUID of the Item to update
    # + headers - Headers to be sent with the request 
    # + return - Successfully deleted an item 
    remote isolated function deleteItem(string vaultUuid, string itemUuid, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Update a subset of Item attributes
    #
    # + vaultUuid - The UUID of the Vault the item is in
    # + itemUuid - The UUID of the Item to update
    # + headers - Headers to be sent with the request 
    # + payload - The list of patch operations to apply to the Item 
    # + return - OK - Item updated. If no Patch operations were provided, Item is unmodified 
    remote isolated function patchItem(string vaultUuid, string itemUuid, PatchItemRequest payload, map<string|string[]> headers = {}) returns FullItem|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get all the files inside an Item
    #
    # + vaultUuid - The UUID of the Vault to fetch Items from
    # + itemUuid - The UUID of the Item to fetch files from
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listItemFiles(string vaultUuid, string itemUuid, map<string|string[]> headers = {}, *ListItemFilesQueries queries) returns File[]|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}/files`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the details of a File
    #
    # + vaultUuid - The UUID of the Vault to fetch Item from
    # + itemUuid - The UUID of the Item to fetch File from
    # + fileUuid - The UUID of the File to fetch
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function getItemFile(string vaultUuid, string itemUuid, string fileUuid, map<string|string[]> headers = {}, *GetItemFileQueries queries) returns File|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}/files/${getEncodedUri(fileUuid)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the content of a File
    #
    # + vaultUuid - The UUID of the Vault the item is in
    # + itemUuid - The UUID of the Item the File is in
    # + fileUuid - UUID of the file to get content from
    # + headers - Headers to be sent with the request 
    # + return - The raw content of the file 
    remote isolated function downloadItemFile(string vaultUuid, string itemUuid, string fileUuid, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/vaults/${getEncodedUri(vaultUuid)}/items/${getEncodedUri(itemUuid)}/files/${getEncodedUri(fileUuid)}/content`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Ping the server for liveness
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getHeartbeat(map<string|string[]> headers = {}) returns string|error {
        string resourcePath = string `/heartbeat`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get state of the server and its dependencies.
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getServerHealth(map<string|string[]> headers = {}) returns ServerHealth|error {
        string resourcePath = string `/health`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Query server for exposed Prometheus metrics
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully returned Prometheus metrics 
    remote isolated function getPrometheusMetrics(map<string|string[]> headers = {}) returns string|error {
        string resourcePath = string `/metrics`;
        return self.clientEp->get(resourcePath, headers);
    }
}
