// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

public type PatchItemRequest PatchInner[];

# Represents the Queries record for the operation: listItemFiles
public type ListItemFilesQueries record {
    # Tells server to return the base64-encoded file contents in the response
    @http:Query {name: "inline_files"}
    boolean inlineFiles?;
};

# Represents the Queries record for the operation: listApiActivity
public type ListApiActivityQueries record {
    # How far into the collection of API Events should the response start
    int offset = 0;
    # How many API Events should be retrieved in a single request
    int 'limit = 50;
};

public type FullItem record {
    *Item;
    File[] files?;
    Field[] fields?;
    FullItem_sections[] sections?;
};

# The item the request accessed
public type APIRequestResourceItem record {
    # The unique id of the item
    @constraint:String {pattern: re `^[\da-z]{26}$`}
    string id?;
};

public type Item record {
    string createdAt?;
    ItemUrls[] urls?;
    @constraint:String {pattern: re `^[\da-z]{26}$`}
    string id?;
    "ARCHIVED"|"DELETED" state?;
    string title?;
    "LOGIN"|"PASSWORD"|"API_CREDENTIAL"|"SERVER"|"DATABASE"|"CREDIT_CARD"|"MEMBERSHIP"|"PASSPORT"|"SOFTWARE_LICENSE"|"OUTDOOR_LICENSE"|"SECURE_NOTE"|"WIRELESS_ROUTER"|"BANK_ACCOUNT"|"DRIVER_LICENSE"|"IDENTITY"|"REWARD_PROGRAM"|"DOCUMENT"|"EMAIL_ACCOUNT"|"SOCIAL_SECURITY_NUMBER"|"MEDICAL_RECORD"|"SSH_KEY"|"CUSTOM" category;
    boolean favorite = false;
    int version?;
    ItemVault vault;
    string lastEditedBy?;
    string[] tags?;
    string updatedAt?;
};

public type Field record {
    # For fields with a purpose of `PASSWORD` this is the entropy of the value
    decimal entropy?;
    # Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types
    ""|"USERNAME"|"PASSWORD"|"NOTES" purpose?;
    # The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
    GeneratorRecipe recipe?;
    FieldSection section?;
    string id;
    string label?;
    "STRING"|"EMAIL"|"CONCEALED"|"URL"|"TOTP"|"DATE"|"MONTH_YEAR"|"MENU" 'type = "STRING";
    string value?;
    # If value is not present then a new value should be generated for this field
    boolean generate = false;
};

# Represents the Queries record for the operation: listVaults
public type ListVaultsQueries record {
    # Filter the Vault collection based on Vault name using SCIM eq filter
    string filter?;
};

public type ServerHealth record {
    string name;
    # The Connect server's version
    string version;
    ServiceDependency[] dependencies?;
};

# The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
public type GeneratorRecipe record {
    # The character sets used to generate the value
    ("LETTERS"|"DIGITS"|"SYMBOLS")[] characterSets?;
    # Length of the generated value
    @constraint:Int {minValue: 1, maxValue: 64}
    int length = 32;
    # List of all characters that should be excluded from generated passwords
    string excludeCharacters?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# The vault the request accessed
public type APIRequestResourceVault record {
    # The unique id of the vault
    @constraint:String {pattern: re `^[\da-z]{26}$`}
    string id?;
};

# The vault or item the request accessed
public type APIRequestResource record {
    # The item the request accessed
    APIRequestResourceItem item?;
    # The version of the item the request accessed
    int itemVersion?;
    # Whether the request accessed an item or a vault
    "ITEM"|"VAULT" 'type?;
    # The vault the request accessed
    APIRequestResourceVault vault?;
};

public type FullItem_sections record {
    string id?;
    string label?;
};

# For files that are in a section, this field describes the section
public type FileSection record {
    # The unique id of the section
    string id?;
};

# The token and client that made the request
public type APIRequestActor record {
    # The user agent of the client that made the request
    string userAgent?;
    # The IP address the request came from
    string requestIp?;
    # The unique id of the token that made the request
    string id?;
    # The id of the 1Password account the token belongs to
    string account?;
    # The unique id of the token, as in the JWT `jti` claim
    string jti?;
};

public type PatchInner record {
    "add"|"remove"|"replace" op;
    # An RFC6901 JSON Pointer pointing to the Item document, an Item Attribute, and Item Field by Field ID, or an Item Field Attribute
    string path;
    # The new value for the attribute or field. It can be any JSON value
    anydata value?;
};

# Represents a request that was made to the API. Including what Token was used and what resource was accessed
public type APIRequest record {
    # Whether the request was allowed or denied
    "SUCCESS"|"DENY" result?;
    # The token and client that made the request
    APIRequestActor actor?;
    # The vault or item the request accessed
    APIRequestResource 'resource?;
    # The unique id used to identify a single request
    string requestId?;
    # The action that was performed on the resource
    "READ"|"CREATE"|"UPDATE"|"DELETE" action?;
    # The time at which the request was processed by the server
    string timestamp?;
};

public type ItemVault record {
    @constraint:String {pattern: re `^[\da-z]{26}$`}
    string id;
};

# Represents the Queries record for the operation: listItems
public type ListItemsQueries record {
    # Filter the Item collection based on Item name using SCIM eq filter
    string filter?;
};

public type Vault record {
    string createdAt?;
    # The vault version
    int attributeVersion?;
    string name?;
    string description?;
    @constraint:String {pattern: re `^[\da-z]{26}$`}
    string id?;
    "USER_CREATED"|"PERSONAL"|"EVERYONE"|"TRANSFER" 'type?;
    # The version of the vault contents
    int contentVersion?;
    # Number of active items in the vault
    int items?;
    string updatedAt?;
};

# Represents the Queries record for the operation: getItemFile
public type GetItemFileQueries record {
    # Tells server to return the base64-encoded file contents in the response
    @http:Query {name: "inline_files"}
    boolean inlineFiles?;
};

# The state of a registered server dependency
public type ServiceDependency record {
    # The name of the dependent service
    string 'service?;
    # Human-readable message for explaining the current state
    string message?;
    # The state of the dependent service, for example ACTIVE
    string status?;
};

public type ItemUrls record {
    string label?;
    string href;
    boolean primary?;
};

public type File record {
    # Size in bytes of the file
    int size?;
    # Name of the file
    string name?;
    # Path of the Connect API that can be used to download the contents of this file
    @jsondata:Name {value: "content_path"}
    string contentPath?;
    # For files that are in a section, this field describes the section
    FileSection section?;
    # ID of the file
    string id?;
    # Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`
    string content?;
};

public type FieldSection record {
    string id?;
};
